column_name_idx: dict[str, int] = {
    'Timestamp': 0,
    'Gender': 1,
    'Location': 2,
    'Hometown': 3,
    'Age': 4,
    'Educational Attainment': 5,
    'College/University Alma Mater': 6,
    'Degree Programme': 7,
    'Academic Learnings': 8,
    'Computer Used Most of the Time': 9,
    'Computer Specs': 10,
    'Operating System': 11,
    'Mac Model': 12,
    'Operating System': 13,
    'Tablet/Smartphone Model': 14,
    'Personal Description': 15,
    'Occupation': 16,
    'Employer Location': 17,
    'Employment Arrangement': 18,
    'Annual Income Range': 19,
    'Annual Income Satisfaction': 20,
    'Academic Arrangement': 21,
    'Length of Programming Experience': 22,
    'Length of Professional Programming Experience': 23,
    'Developer Type': 24,
    'Developer Activities': 25,
    'Languages Used, Loved, and Hated [Ada]': 26,
    'Languages Used, Loved, and Hated [Apex]': 27,
    'Languages Used, Loved, and Hated [APL]': 28,
    'Languages Used, Loved, and Hated [Assembly]': 29,
    'Languages Used, Loved, and Hated [C]': 30,
    'Languages Used, Loved, and Hated [C++]': 31,
    'Languages Used, Loved, and Hated [C#]': 32,
    'Languages Used, Loved, and Hated [Clojure]': 33,
    'Languages Used, Loved, and Hated [Cobol]': 34,
    'Languages Used, Loved, and Hated [Crystal]': 35,
    'Languages Used, Loved, and Hated [Dart]': 36,
    'Languages Used, Loved, and Hated [DataWeave]': 37,
    'Languages Used, Loved, and Hated [Delphi]': 38,
    'Languages Used, Loved, and Hated [Elixir]': 39,
    'Languages Used, Loved, and Hated [Erlang]': 40,
    'Languages Used, Loved, and Hated [F#]': 41,
    'Languages Used, Loved, and Hated [Flow]': 42,
    'Languages Used, Loved, and Hated [Fortran]': 43,
    'Languages Used, Loved, and Hated [GDScript]': 44,
    'Languages Used, Loved, and Hated [Go]': 45,
    'Languages Used, Loved, and Hated [Groovy]': 46,
    'Languages Used, Loved, and Hated [Haskell]': 47,
    'Languages Used, Loved, and Hated [HTML/CSS]': 48,
    'Languages Used, Loved, and Hated [Java]': 49,
    'Languages Used, Loved, and Hated [JavaScript]': 50,
    'Languages Used, Loved, and Hated [Julia]': 51,
    'Languages Used, Loved, and Hated [Kotlin]': 52,
    'Languages Used, Loved, and Hated [LISP]': 53,
    'Languages Used, Loved, and Hated [Lua]': 54,
    'Languages Used, Loved, and Hated [MATLAB]': 55,
    'Languages Used, Loved, and Hated [Nim]': 56,
    'Languages Used, Loved, and Hated [Objective-C]': 57,
    'Languages Used, Loved, and Hated [OCaml]': 58,
    'Languages Used, Loved, and Hated [Perl]': 59,
    'Languages Used, Loved, and Hated [PHP]': 60,
    'Languages Used, Loved, and Hated [PowerShell]': 61,
    'Languages Used, Loved, and Hated [Prolog]': 62,
    'Languages Used, Loved, and Hated [Python]': 63,
    'Languages Used, Loved, and Hated [Ruby]': 64,
    'Languages Used, Loved, and Hated [R]': 65,
    'Languages Used, Loved, and Hated [Raku]': 66,
    'Languages Used, Loved, and Hated [Rust]': 67,
    'Languages Used, Loved, and Hated [SAS]': 68,
    'Languages Used, Loved, and Hated [Scala]': 69,
    'Languages Used, Loved, and Hated [Shell (e.g. Bash, ZSH)]': 70,
    'Languages Used, Loved, and Hated [Solidity]': 71,
    'Languages Used, Loved, and Hated [SQL]': 72,
    'Languages Used, Loved, and Hated [Swift]': 73,
    'Languages Used, Loved, and Hated [SystemVerilog]': 74,
    'Languages Used, Loved, and Hated [TypeScript]': 75,
    'Languages Used, Loved, and Hated [Verilog]': 76,
    'Languages Used, Loved, and Hated [Visual Basic (6 or earlier)]': 77,
    'Languages Used, Loved, and Hated [Visual Basic .NET]': 78,
    'Languages Used, Loved, and Hated [VBA]': 79,
    'Languages Used, Loved, and Hated [Zig]': 80,
    'Primary Languages': 81,
    'Software Being Developed': 82,
    'Platforms': 83,
    'Frameworks and Libraries [.NET 5+]': 84,
    'Frameworks and Libraries [.NET Framework 1.0 - 4.8]': 85,
    'Frameworks and Libraries [.NET MAUI]': 86,
    'Frameworks and Libraries [Angular]': 87,
    'Frameworks and Libraries [AngularJS]': 88,
    'Frameworks and Libraries [Apache Kafka]': 89,
    'Frameworks and Libraries [Apache Spark]': 90,
    'Frameworks and Libraries [ASP.Net]': 91,
    'Frameworks and Libraries [ASP.Net Core]': 92,
    'Frameworks and Libraries [bandit]': 93,
    'Frameworks and Libraries [Blazor]': 94,
    'Frameworks and Libraries [Boost.Test]': 95,
    'Frameworks and Libraries [Capacitor]': 96,
    'Frameworks and Libraries [Catch]': 97,
    'Frameworks and Libraries [CodeIgniter]': 98,
    'Frameworks and Libraries [Compose Multiplatform]': 99,
    'Frameworks and Libraries [Cordova]': 100,
    'Frameworks and Libraries [cppunit]': 101,
    'Frameworks and Libraries [CUDA]': 102,
    'Frameworks and Libraries [Deno]': 103,
    'Frameworks and Libraries [DirectX 12]': 104,
    'Frameworks and Libraries [DirectX 9 - 11]': 105,
    'Frameworks and Libraries [Django]': 106,
    'Frameworks and Libraries [doctest]': 107,
    'Frameworks and Libraries [Drupal]': 108,
    'Frameworks and Libraries [Electron]': 109,
    'Frameworks and Libraries [ELFspy]': 110,
    'Frameworks and Libraries [Elm]': 111,
    'Frameworks and Libraries [Express]': 112,
    'Frameworks and Libraries [FastAPI]': 113,
    'Frameworks and Libraries [Fastify]': 114,
    'Frameworks and Libraries [Flask]': 115,
    'Frameworks and Libraries [Flutter]': 116,
    'Frameworks and Libraries [Gatsby]': 117,
    'Frameworks and Libraries [GLFW]': 118,
    'Frameworks and Libraries [Google Test]': 119,
    'Frameworks and Libraries [GTK]': 120,
    'Frameworks and Libraries [Hadoop]': 121,
    'Frameworks and Libraries [Hugging Face Transformers]': 122,
    'Frameworks and Libraries [Ionic]': 123,
    'Frameworks and Libraries [JAX]': 124,
    'Frameworks and Libraries [jQuery]': 125,
    'Frameworks and Libraries [Keras]': 126,
    'Frameworks and Libraries [Kotlin Multiplatform]': 127,
    'Frameworks and Libraries [Kivy]': 128,
    'Frameworks and Libraries [Ktor]': 129,
    'Frameworks and Libraries [Laravel]': 130,
    'Frameworks and Libraries [liblittletest]': 131,
    'Frameworks and Libraries [Lit]': 132,
    'Frameworks and Libraries [Metal]': 133,
    'Frameworks and Libraries [MFC]': 134,
    'Frameworks and Libraries [Micronaut]': 135,
    'Frameworks and Libraries [NestJS]': 136,
    'Frameworks and Libraries [Next.js]': 137,
    'Frameworks and Libraries [Node.js]': 138,
    'Frameworks and Libraries [NumPy]': 139,
    'Frameworks and Libraries [Nuxt.js]': 140,
    'Frameworks and Libraries [OpenCL]': 141,
    'Frameworks and Libraries [OpenCV]': 142,
    'Frameworks and Libraries [OpenGL]': 143,
    'Frameworks and Libraries [Pandas]': 144,
    'Frameworks and Libraries [Phoenix]': 145,
    'Frameworks and Libraries [Play Framework]': 146,
    'Frameworks and Libraries [Qt]': 147,
    'Frameworks and Libraries [Quarkus]': 148,
    'Frameworks and Libraries [Qwik]': 149,
    'Frameworks and Libraries [RabbitMQ]': 150,
    'Frameworks and Libraries [React]': 151,
    'Frameworks and Libraries [React Native]': 152,
    'Frameworks and Libraries [Remix]': 153,
    'Frameworks and Libraries [Ruby on Rails]': 154,
    'Frameworks and Libraries [SciKit-Learn]': 155,
    'Frameworks and Libraries [SDL]': 156,
    'Frameworks and Libraries [SFML]': 157,
    'Frameworks and Libraries [snitch]': 158,
    'Frameworks and Libraries [Solid.js]': 159,
    'Frameworks and Libraries [Spring Boot]': 160,
    'Frameworks and Libraries [Spring Framework]': 161,
    'Frameworks and Libraries [Svelte]': 162,
    'Frameworks and Libraries [SwiftUI]': 163,
    'Frameworks and Libraries [Symfony]': 164,
    'Frameworks and Libraries [Tauri]': 165,
    'Frameworks and Libraries [TensorFlow]': 166,
    'Frameworks and Libraries [Tidyverse]': 167,
    'Frameworks and Libraries [Torch/PyTorch]': 168,
    'Frameworks and Libraries [Uno Platform]': 169,
    'Frameworks and Libraries [Vue.js]': 170,
    'Frameworks and Libraries [Vulkan]': 171,
    'Frameworks and Libraries [WordPress]': 172,
    'Frameworks and Libraries [Xamarin]': 173,
    'Tools [Ansible]': 174,
    'Tools [Ant]': 175,
    'Tools [APT]': 176,
    'Tools [build2]': 177,
    'Tools [Bun]': 178,
    'Tools [Cargo]': 179,
    'Tools [Chef]': 180,
    'Tools [Chocolatey]': 181,
    'Tools [CMake]': 182,
    'Tools [Composer]': 183,
    'Tools [Dagger]': 184,
    'Tools [Docker]': 185,
    'Tools [GNU GCC]': 186,
    'Tools [Godot]': 187,
    'Tools [Gradle]': 188,
    'Tools [Homebrew]': 189,
    'Tools [Kubernetes]': 190,
    'Tools [LLVM Clang]': 191,
    'Tools [Make]': 192,
    'Tools [Maven]': 193,
    'Tools [Meson]': 194,
    'Tools [MSBuild]': 195,
    'Tools [MSVC]': 196,
    'Tools [Ninja]': 197,
    'Tools [Nix]': 198,
    'Tools [npm]': 199,
    'Tools [NuGet]': 200,
    'Tools [Pacman]': 201,
    'Tools [Pip]': 202,
    'Tools [pnpm]': 203,
    'Tools [Podman]': 204,
    'Tools [Pulumi]': 205,
    'Tools [Puppet]': 206,
    'Tools [QMake]': 207,
    'Tools [Scons]': 208,
    'Tools [Terraform]': 209,
    'Tools [Unity 3D]': 210,
    'Tools [Unreal Engine]': 211,
    'Tools [Vite]': 212,
    'Tools [Wasmer]': 213,
    'Tools [Webpack]': 214,
    'Tools [Yarn]': 215,
    'IDEs and Text Editors [Android Studio]': 216,
    'IDEs and Text Editors [Atom]': 217,
    'IDEs and Text Editors [BBEdit]': 218,
    'IDEs and Text Editors [CLion]': 219,
    'IDEs and Text Editors [Code::Blocks]': 220,
    'IDEs and Text Editors [condo]': 221,
    'IDEs and Text Editors [DataGrip]': 222,
    'IDEs and Text Editors [Eclipse]': 223,
    'IDEs and Text Editors [Emacs]': 224,
    'IDEs and Text Editors [Fleet]': 225,
    'IDEs and Text Editors [Geany]': 226,
    'IDEs and Text Editors [Goland]': 227,
    'IDEs and Text Editors [Helix]': 228,
    'IDEs and Text Editors [IntelliJ IDEA]': 229,
    'IDEs and Text Editors [IPython]': 230,
    'IDEs and Text Editors [Jupyter Notebook/JupyterLab]': 231,
    'IDEs and Text Editors [Kate]': 232,
    'IDEs and Text Editors [Micro]': 233,
    'IDEs and Text Editors [Nano]': 234,
    'IDEs and Text Editors [Neovim]': 235,
    'IDEs and Text Editors [NetBeans]': 236,
    'IDEs and Text Editors [Notepad++]': 237,
    'IDEs and Text Editors [Nova]': 238,
    'IDEs and Text Editors [PhpStorm]': 239,
    'IDEs and Text Editors [PyCharm]': 240,
    'IDEs and Text Editors [Qt Creator]': 241,
    'IDEs and Text Editors [RAD Studio]': 242,
    'IDEs and Text Editors [Rider]': 243,
    'IDEs and Text Editors [RStudio]': 244,
    'IDEs and Text Editors [RubyMine]': 245,
    'IDEs and Text Editors [RustRover]': 246,
    'IDEs and Text Editors [Spyder]': 247,
    'IDEs and Text Editors [Sublime Text]': 248,
    'IDEs and Text Editors [TextMate]': 249,
    'IDEs and Text Editors [Vim]': 250,
    'IDEs and Text Editors [Visual Studio]': 251,
    'IDEs and Text Editors [Visual Studio Code]': 252,
    'IDEs and Text Editors [VSCodium]': 253,
    'IDEs and Text Editors [WebStorm]': 254,
    'IDEs and Text Editors [Xcode]': 255,
    'Databases Used, Loved, and Hated [BigQuery]': 256,
    'Databases Used, Loved, and Hated [Cassandra]': 257,
    'Databases Used, Loved, and Hated [Clickhouse]': 258,
    'Databases Used, Loved, and Hated [Cloud Firestore]': 259,
    'Databases Used, Loved, and Hated [CockroachDB]': 260,
    'Databases Used, Loved, and Hated [Cosmos DB]': 261,
    'Databases Used, Loved, and Hated [CouchDB]': 262,
    'Databases Used, Loved, and Hated [Datomic]': 263,
    'Databases Used, Loved, and Hated [DuckDB]': 264,
    'Databases Used, Loved, and Hated [DynamoDB]': 265,
    'Databases Used, Loved, and Hated [ElasticSearch]': 266,
    'Databases Used, Loved, and Hated [Firebase Realtime Database]': 267,
    'Databases Used, Loved, and Hated [Firebird]': 268,
    'Databases Used, Loved, and Hated [H2]': 269,
    'Databases Used, Loved, and Hated [IBM DB2]': 270,
    'Databases Used, Loved, and Hated [InfluxDB]': 271,
    'Databases Used, Loved, and Hated [MariaDB]': 272,
    'Databases Used, Loved, and Hated [Microsoft Access]': 273,
    'Databases Used, Loved, and Hated [Microsoft SQL Server]': 274,
    'Databases Used, Loved, and Hated [MongoDB]': 275,
    'Databases Used, Loved, and Hated [MySQL]': 276,
    'Databases Used, Loved, and Hated [Neo4J]': 277,
    'Databases Used, Loved, and Hated [Oracle]': 278,
    'Databases Used, Loved, and Hated [PostgreSQL]': 279,
    'Databases Used, Loved, and Hated [RavenDB]': 280,
    'Databases Used, Loved, and Hated [Redis]': 281,
    'Databases Used, Loved, and Hated [Snowflake]': 282,
    'Databases Used, Loved, and Hated [Solr]': 283,
    'Databases Used, Loved, and Hated [SQLite]': 284,
    'Databases Used, Loved, and Hated [Supabase]': 285,
    'Databases Used, Loved, and Hated [Text Files]': 286,
    'Databases Used, Loved, and Hated [TiDB]': 287,
    'Cloud Platforms Used, Loved, and Hated [Amazon Web Services (AWS)]': 288,
    'Cloud Platforms Used, Loved, and Hated [Cloudflare]': 289,
    'Cloud Platforms Used, Loved, and Hated [Colocation]': 290,
    'Cloud Platforms Used, Loved, and Hated [DigitalOcean]': 291,
    'Cloud Platforms Used, Loved, and Hated [Firebase]': 292,
    'Cloud Platforms Used, Loved, and Hated [Fly.io]': 293,
    'Cloud Platforms Used, Loved, and Hated [Google Cloud Platform]': 294,
    'Cloud Platforms Used, Loved, and Hated [Heroku]': 295,
    'Cloud Platforms Used, Loved, and Hated [Hetzner]': 296,
    'Cloud Platforms Used, Loved, and Hated [IBM Cloud or Watson]': 297,
    'Cloud Platforms Used, Loved, and Hated [Linode (now Akamai)]': 298,
    'Cloud Platforms Used, Loved, and Hated [Managed Hosting]': 299,
    'Cloud Platforms Used, Loved, and Hated [Microsoft Azure]': 300,
    'Cloud Platforms Used, Loved, and Hated [Netlify]': 301,
    'Cloud Platforms Used, Loved, and Hated [OpenShift]': 302,
    'Cloud Platforms Used, Loved, and Hated [OpenStack]': 303,
    'Cloud Platforms Used, Loved, and Hated [Oracle Cloud Infrastructure]': 304,
    'Cloud Platforms Used, Loved, and Hated [OVH]': 305,
    'Cloud Platforms Used, Loved, and Hated [Render]': 306,
    'Cloud Platforms Used, Loved, and Hated [Scaleway]': 307,
    'Cloud Platforms Used, Loved, and Hated [Self-Hosted]': 308,
    'Cloud Platforms Used, Loved, and Hated [Vercel]': 309,
    'Cloud Platforms Used, Loved, and Hated [VMware]': 310,
    'Cloud Platforms Used, Loved, and Hated [Vultr]': 311,
    'Work Management and Code Documentation [Adobe Workfront]': 312,
    'Work Management and Code Documentation [Airtable]': 313,
    'Work Management and Code Documentation [Asana]': 314,
    'Work Management and Code Documentation [Azure DevOps]': 315,
    'Work Management and Code Documentation [Basecamp]': 316,
    'Work Management and Code Documentation [Cerri]': 317,
    'Work Management and Code Documentation [ClickUp]': 318,
    'Work Management and Code Documentation [Confluence]': 319,
    'Work Management and Code Documentation [Dingtalk (Teambition)]': 320,
    'Work Management and Code Documentation [Document360]': 321,
    'Work Management and Code Documentation [Doxygen]': 322,
    'Work Management and Code Documentation [GitHub Discussions]': 323,
    'Work Management and Code Documentation [Jira]': 324,
    'Work Management and Code Documentation [Leankor]': 325,
    'Work Management and Code Documentation [Linear]': 326,
    'Work Management and Code Documentation [Markdown File]': 327,
    'Work Management and Code Documentation [Microsoft Lists]': 328,
    'Work Management and Code Documentation [Microsoft Planner]': 329,
    'Work Management and Code Documentation [Miro]': 330,
    'Work Management and Code Documentation [Monday.com]': 331,
    'Work Management and Code Documentation [Notion]': 332,
    'Work Management and Code Documentation [Nuclino]': 333,
    'Work Management and Code Documentation [Planview Projectplace or Clarizen]': 334,
    'Work Management and Code Documentation [Redmine]': 335,
    'Work Management and Code Documentation [Redocly]': 336,
    'Work Management and Code Documentation [Shortcut]': 337,
    'Work Management and Code Documentation [Smartsheet]': 338,
    'Work Management and Code Documentation [StackOverflow for Teams]': 339,
    'Work Management and Code Documentation [Swit]': 340,
    'Work Management and Code Documentation [Tettra]': 341,
    'Work Management and Code Documentation [Trello]': 342,
    'Work Management and Code Documentation [Wikis]': 343,
    'Work Management and Code Documentation [Wimi]': 344,
    'Work Management and Code Documentation [Workzone]': 345,
    'Work Management and Code Documentation [Wrike]': 346,
    'Work Management and Code Documentation [YouTrack]': 347,
    'Communication Tools [Cisco Webex Teams]': 348,
    'Communication Tools [Coolfire Core]': 349,
    'Communication Tools [Discord]': 350,
    'Communication Tools [Facebook Messenger]': 351,
    'Communication Tools [Google Chat]': 352,
    'Communication Tools [Google Meet]': 353,
    'Communication Tools [IRC]': 354,
    'Communication Tools [Jitsi]': 355,
    'Communication Tools [Matrix]': 356,
    'Communication Tools [Mattermost]': 357,
    'Communication Tools [Microsoft Teams]': 358,
    'Communication Tools [Ringcentral]': 359,
    'Communication Tools [Rocketchat]': 360,
    'Communication Tools [Signal]': 361,
    'Communication Tools [Skype]': 362,
    'Communication Tools [Slack]': 363,
    'Communication Tools [Symphony]': 364,
    'Communication Tools [Telegram]': 365,
    'Communication Tools [Unify Circuit]': 366,
    'Communication Tools [Whatsapp]': 367,
    'Communication Tools [Wickr]': 368,
    'Communication Tools [Wire]': 369,
    'Communication Tools [Zoom]': 370,
    'Communication Tools [Zulip]': 371,
    'Local CS/IT Sentiments': 372,
    'Tech Events in the Region': 373,
    'Topics': 374,
    'AI Search Tools [Andi]': 375,
    'AI Search Tools [Bing AI]': 376,
    'AI Search Tools [ChatGPT]': 377,
    'AI Search Tools [Google Bard AI]': 378,
    'AI Search Tools [Metaphor]': 379,
    'AI Search Tools [Neeva AI]': 380,
    'AI Search Tools [Perplexity AI]': 381,
    'AI Search Tools [Phind]': 382,
    'AI Search Tools [Quora Poe]': 383,
    'AI Search Tools [WolframAlpha]': 384,
    'AI Search Tools [You.com]': 385,
    'AI Search Tools [Others]': 386,
    'AI Developer Tools [Adrenaline]': 387,
    'AI Developer Tools [AWS CodeWhisperer]': 388,
    'AI Developer Tools [Codeium]': 389,
    'AI Developer Tools [GitHub Copilot]': 390,
    'AI Developer Tools [Mintlify]': 391,
    'AI Developer Tools [Replit Ghostwriter]': 392,
    'AI Developer Tools [Rubber Duck.AI]': 393,
    'AI Developer Tools [Synk Code]': 394,
    'AI Developer Tools [TabNine]': 395,
    'AI Developer Tools [Whispr AI]': 396,
    'AI Developer Tools [Others]': 397,
    'AI Datasets': 398,
    'AI Art': 399,
    'AI Code Generation': 400,
    'Survey Length': 401,
    'Survey Difficulty': 402,
    'Event Food and Drinks': 403,
    'Event Location': 404,
    'Message for Dev8': 405
}
